language: node_js
node_js:
- 14.16
script:
- npm run lint
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: 2ff3470d-0f4e-49ab-a81d-57f8a020efcb
  strategy: git
  app:
    maine: calendarfinance
